

# 📔 **Resolución**
Una vez que la nota sea entregada, encontrarás la resolución en este link de notion:

https://www.notion.so/Soluciones-MMIA-3era-cohorte-1ea0573743578016a1aac56aaf239271?source=copy_link

Recuerda que existen varias formar de solucionar las actividades propuestas en los laboratorios. Toma la resolución entregada como referencia. En caso de que el link de resolución no esté público, solicita acceso en el mismo link de notion

# Optimización de hiperparámetros con PCA y sin PCA para la predicción de pérdida de clientes en Empresas de Servicios de Telecomunicaciones (Churn) con KNN


Reducir las salidas y [deserciones de clientes](https://www.bain.com/insights/breaking-the-back-of-customer-churn/) se ha convertido en una alta prioridad para la mayoría de los proveedores de servicios de comunicaciones a medida que los mercados maduran y la competencia se intensifica.




En este documento usaremos una base de datos de una empresa de telecomunicaciones anónima [disponibilizada por IBM](https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv).

El principal objetivo es crear un model de aprendizaje automático basado en KNN (similar al propuesto [aquí con SVM](https://github.com/mmcuri/ds_handson/blob/master/Telecom_Churn_Prediction.ipynb)) para predecir la pérdida o salida de clientes en una empresa de telecomunicaciones.

## Librerías

Importamos varias bibliotecas y módulos útiles para el análisis de datos y el aprendizaje automático en Python. A continuación se describe cada uno de ellos:

- `pandas as pd`: Importa la biblioteca Pandas y la renombra como "pd". Pandas es una biblioteca popular utilizada para la manipulación y análisis de datos en Python.

- `numpy as np`: Importa la biblioteca NumPy y la renombra como "np". NumPy es una biblioteca de Python utilizada para realizar operaciones matemáticas en matrices y vectores.

- `matplotlib.pyplot as plt`: Importa la biblioteca Matplotlib y el módulo pyplot y lo renombra como "plt". Matplotlib es una biblioteca utilizada para la visualización de datos en Python.

- `from sklearn.metrics import classification_report`: Importa la función classification_report desde el módulo metrics de la biblioteca scikit-learn. classification_report es una función que calcula y muestra un informe de clasificación detallado para un modelo de clasificación.

- `from sklearn.metrics import confusion_matrix`: Importa la función confusion_matrix desde el módulo metrics de la biblioteca scikit-learn. confusion_matrix es una función que calcula y muestra la matriz de confusión para un modelo de clasificación.

- `from sklearn.metrics import accuracy_score`: Importa la función accuracy_score desde el módulo metrics de la biblioteca scikit-learn. accuracy_score es una función que calcula y muestra la precisión de un modelo de clasificación.

- `from sklearn.metrics import roc_auc_score`: Importa la función roc_auc_score desde el módulo metrics de la biblioteca scikit-learn. roc_auc_score es una función que calcula el área bajo la curva ROC (AUC) para un modelo de clasificación.

- `from sklearn.preprocessing import StandardScaler, LabelEncoder`: Importa las clases StandardScaler y LabelEncoder desde el módulo preprocessing de la biblioteca scikit-learn. StandardScaler es una clase utilizada para estandarizar los datos y LabelEncoder es una clase utilizada para codificar las etiquetas de clase en números enteros.

- `from sklearn.model_selection import train_test_split`: Importa la función train_test_split desde el módulo model_selection de la biblioteca scikit-learn. train_test_split es una función que divide los datos en conjuntos de entrenamiento y prueba para su uso en el modelado predictivo.

En resumen, este código importa varias bibliotecas y módulos que son útiles para el análisis de datos y el aprendizaje automático en Python.

In [ ]:
# importing libraries
import pandas as pd #excel sofisticado
import numpy as np #matlab
import matplotlib.pyplot as plt #plots
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

## Base de datos

Este conjunto de datos contiene un total de 7043 clientes y 21 características de los mismos. De las entradas, 5174 son clientes activos y 1869 son clientes que la empresa ha perdido. Observe que el conjunto de datos está desbalanceado pues por cada cliente perdido existe casi 3 clientes activos. La variable de salida para nuestro modelo de machine learning será `Churn`.

In [ ]:
# importamos dataset
DATA_PATH = "https://raw.githubusercontent.com/mtgca/datasets_public/main/WA_Fn-UseC_-Telco-Customer-Churn.csv"
df = pd.read_csv(DATA_PATH)
#print(df)
# vemos las primeras 5 filas
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

### *Detalles de la base de datos*

*	`customerID` - Custumer unique identifier
*	`gender` - Customer gender - ['Female' 'Male']
*	`SeniorCitizen` - Elderly or retired person, a senior citizen is someone who has at least attained the age of 60 of 65 years
*	`Partner` - - ['No' 'Yes']
*	`Dependents` - If customer has dependents - ['No' 'Yes']
*	`Tenure` - Customer lifespan (in months)
*	`PhoneService` - - ['No' 'Yes']
*	`MultipleLines` - - ['No' 'No phone service' 'Yes']
*	`InternetService` - - ['No' 'No internet service' 'Yes']
*	`OnlineSecurity` - - ['No' 'No internet service' 'Yes']
*	`OnlineBackup` - - ['No' 'No internet service' 'Yes']
*	`DeviceProtection` - - ['No' 'No internet service' 'Yes']
*	`TechSupport` - - ['No' 'No internet service' 'Yes']
*	`StreamingTV` - - ['No' 'No internet service' 'Yes']
*	`StreamingMovies` -  - ['No' 'No internet service' 'Yes']
*	`Contract` - Type of contract - ['Month-to-month' 'One year' 'Two year']
*	`PaperlessBilling` - - ['No' 'Yes']
*	`PaymentMethod` - payment method - ['Bank transfer (automatic)', 'Credit card (automatic)', 'Electronic check', 'Mailed check']
*	`MonthlyCharges` - Monthly Recurring Charges
*	`TotalCharges` - Life time value
*	`Churn` - Churn value, the targer vector - ['No' 'Yes']

### *Limpieza del Dataset*

El código presenta una serie de operaciones de preprocesamiento de datos en una base de datos que contiene información sobre clientes de una compañía, incluyendo su género, edad, servicios contratados, pagos realizados, entre otros.

En primer lugar, se define la función get_df_size para imprimir el número de atributos y entradas de la base de datos.

Luego, se reemplazan los valores en blanco por NaN para facilitar el manejo de valores faltantes en la base de datos.

A continuación, se reemplazan los valores faltantes en la columna 'TotalCharges' por la mediana de esa columna y se convierte esa columna al tipo numérico.

Después, se elimina la columna 'customerID' ya que no es una característica relevante.

A continuación, se codifican las características binarias en 0's y 1's usando LabelEncoder y se imprimen las categorías correspondientes a cada una de estas características.

In [ ]:
def get_df_size(df, header='Dataset dimensions'):
  print(header,
        '\n# Attributes: ', df.shape[1],
        '\n# Entries: ', df.shape[0],'\n')

get_df_size(df)

#df.info()

# reemplaza valores en blanco por NaN
df_clean = df.replace(r'^\s*$', np.nan, regex=True)

# Convert 'TotalCharges' to numeric before calculating the median.
# errors='coerce' will handle any non-numeric values by setting them to NaN.
df_clean['TotalCharges'] = pd.to_numeric(df_clean['TotalCharges'], errors='coerce')

# reemplaza valores faltantes en TotalCharges por la mediana de TotalCharges.
total_charges_median = df_clean.TotalCharges.median()
df_clean['TotalCharges'].fillna(total_charges_median, inplace=True)
df_clean['TotalCharges'] = df_clean['TotalCharges'].apply(pd.to_numeric)

#CustomerID lo retiramos porque no es una característica
df_clean = df_clean.drop('customerID', axis=1)
df_clean.describe()

print("Churn No Instances: ", df_clean[df_clean['Churn'] == 'No'].shape[0])
print("Churn Yes Instances: ", df_clean[df_clean['Churn'] == 'Yes'].shape[0])

binary_feat = df_clean.nunique()[df_clean.nunique() == 2].keys().tolist()
numeric_feat = [col for col in df_clean.select_dtypes(['float','int']).columns.tolist() if col not in binary_feat]
categorical_feat = [ col for col in df_clean.select_dtypes('object').columns.to_list() if col not in binary_feat + numeric_feat ]
df_proc = df_clean.copy()
#Etiquetas para características binarias
le = LabelEncoder()
for i in binary_feat:
  df_proc[i] = le.fit_transform(df_proc[i])
  print(i, '\n', np.unique(df_proc[i].values))
#Dummy variables
df_proc = pd.get_dummies(df_proc, columns=categorical_feat)
get_df_size(df, header='Original dataset:')
get_df_size(df_proc, header='Processed dataset:')
df_proc.head()

Dataset dimensions
# Attributes:  21
# Entries:  7043

<ipython-input-3-e2673bf5fe09>:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['TotalCharges'].fillna(total_charges_median, inplace=True)

Churn No Instances:  5174
Churn Yes Instances:  1869
gender
 [0 1]
SeniorCitizen
 [0 1]
Partner
 [0 1]
Dependents
 [0 1]
PhoneService
 [0 1]
PaperlessBilling
 [0 1]
Churn
 [0 1]
Original dataset:
# Attributes:  21
# Entries:  7043

Processed dataset:
# Attributes:  41
# Entries:  7043

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,StreamingMovies_No,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,1,29.85,29.85,0,...,True,False,False,True,False,False,False,False,True,False
1,1,0,0,0,34,1,0,56.95,1889.50,0,...,True,False,False,False,True,False,False,False,False,True
2,1,0,0,0,2,1,1,53.85,108.15,1,...,True,False,False,True,False,False,False,False,False,True
3,1,0,0,0,45,0,0,42.30,1840.75,0,...,True,False,False,False,True,False,True,False,False,False
4,0,0,0,0,2,1,1,70.70,151.65,1,...,True,False,False,True,False,False,False,False,True,False

### *División en conjunto de entrenamiento y test*

En el código, se divide el conjunto de datos df_proc en características y variable objetivo X e y, respectivamente. Luego, se realiza una división de los datos en conjuntos de entrenamiento y prueba utilizando la función train_test_split de scikit-learn. Los conjuntos de entrenamiento y prueba se almacenan en X_train, X_test, y_train y y_test. La división se realiza de manera estratificada para asegurar que la proporción de instancias positivas y negativas en la variable objetivo se mantenga en ambos conjuntos. Se utiliza una proporción de 80/20 para los conjuntos de entrenamiento y prueba, respectivamente, y se fija una semilla aleatoria (random_state) en 42 para asegurar que los resultados sean reproducibles.

In [ ]:
# dividimos df_proc en características y salida
X=df_proc.drop('Churn', axis=1) #features
y=df_proc['Churn'] #output, target

# Dividimos el conjunto de entrenamiento y test
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

### *Balanceo de datos*

Este código realiza el submuestreo (undersampling) de un conjunto de datos desbalanceado en términos de la variable objetivo. El submuestreo se utiliza para abordar el problema del desequilibrio de clases en el conjunto de datos, donde una o varias clases tienen muchas menos observaciones que las otras clases. En este caso, el modelo de aprendizaje automático puede estar sesgado hacia la clase mayoritaria, lo que puede resultar en un rendimiento deficiente en la clasificación de la clase minoritaria.

El submuestreo implica reducir el número de observaciones en la clase mayoritaria para equilibrar la distribución de las clases en el conjunto de datos. Esto puede mejorar el rendimiento del modelo en la clasificación de la clase minoritaria y reducir el sesgo hacia la clase mayoritaria.

La biblioteca imblearn se utiliza para realizar el submuestreo, y en este caso se importa la clase RandomUnderSampler. El objeto RandomUnderSampler se inicializa con random_state=1, lo que garantiza que los resultados serán reproducibles.

Luego, el submuestreo se realiza en el conjunto de entrenamiento (X_train, y_train) mediante el método fit_resample del objeto rus. Los datos submuestreados se almacenan en X_train_rus y y_train_rus.

Para evaluar el efecto del submuestreo, se utiliza la función get_df_size, que devuelve el tamaño del conjunto de datos. Primero se imprime el tamaño del conjunto de entrenamiento original (X_train, y_train) antes del submuestreo, y luego se imprime el tamaño del conjunto submuestreado (X_train_rus, y_train_rus) después de aplicar el submuestreo.

Finalmente, se utiliza la función np.unique para verificar que las categorías de la variable objetivo (y_train_rus) estén balanceadas. La función devuelve una tupla que contiene las categorías únicas y el número de instancias en cada categoría. Al utilizar return_counts=True, se garantiza que se devuelvan los recuentos de las categorías.

In [ ]:
# submuestreo -> under sampling
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=1)
X_train_undersampled, y_train_undersampled = rus.fit_resample(X_train, y_train)
get_df_size(X_train, header='Before balancing:')
get_df_size(X_train_undersampled, header='After balancing:')

# verificamos que las categorias estén balanceadas
np.unique(y_train_undersampled, return_counts=True)

Before balancing:
# Attributes:  40
# Entries:  5634

After balancing:
# Attributes:  40
# Entries:  2990

(array([0, 1]), array([1495, 1495]))

## Modelo de Machine Learning

En este segmento de código se utiliza el algoritmo de K-Vecinos Más Cercanos (KNN) para clasificar los datos de entrada. Primero, se crea un objeto de Pipeline que combina varios pasos de preprocesamiento y entrenamiento del modelo. Los pasos incluyen:

`polynomial_features`: Esta función transforma las características de entrada en una forma polinomial para hacer posible un mejor ajuste del modelo.

`scaler`: Normaliza las características de entrada para que todas tengan una media cero y una varianza unitaria.

`knn`: Un clasificador KNN que utiliza un número especificado de vecinos para determinar la clase de un punto de datos.

Una vez que se define el objeto de Pipeline, se ajusta al conjunto de entrenamiento utilizando el método fit(). Luego se utiliza el modelo ajustado para predecir las clases de los puntos de datos en el conjunto de prueba y en el conjunto de entrenamiento. Esto se hace mediante el método predict(). Finalmente, se utiliza la métrica de precisión (accuracy_score) de la biblioteca sklearn.metrics para evaluar la precisión del modelo en el conjunto de prueba y en el conjunto de entrenamiento.

### K Nearest Neighbors sin optimización de hiperparámetros

In [ ]:

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
import sklearn.metrics as metrics
from sklearn.preprocessing import PolynomialFeatures

# pipeline
pipeline_knn = Pipeline([
    # ('polynomial_features', PolynomialFeatures(degree=2)),
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier()) #parámetros por default
])

# training
pipeline_knn.fit(X_train_undersampled, y_train_undersampled)

# evaluation on test
pred_test = pipeline_knn.predict(X_test)
f1score = metrics.f1_score(y_test, pred_test)
acc = metrics.accuracy_score(y_test, pred_test)
preci = metrics.precision_score(y_test, pred_test)
recall = metrics.recall_score(y_test, pred_test)

print("Para el modelo NO optimizado, métricas en el conjunto de test: recall = ", recall, ", F1 = ", f1score, ", acc = ", acc, ", precision = ", preci, )

Para el modelo NO optimizado, métricas en el conjunto de test: recall =  0.7727272727272727 , F1 =  0.5639024390243902 , acc =  0.6827537260468417 , precision =  0.44393241167434716

### Optimización de Hiperparámetros KNN con kfold CV sin PCA

Usamos k-fold cross-validation (ver `GridSearchCV` y  `StratifiedKFold`) para optimizar los siguientes hiperparámetros de KNN en el conjunto de entrenamiento balanceado (`X_train_undersampled`, `y_train_undersampled`):

1. Ponderación de vecinos: sin ponderación, ponderación del inverso de la distancia
2. Número de vecinos: rango 1 a 100.
3. Métricas de distancia: euclideana, manhattan, coseno

Para la optimización de hiperparámetros utilizamos como métrica al recall.

Una vez optimizados los hiperparámetros, reentrenamos el clasificador de kNN con los mejores hiperparámetros encontrados. Finalmente, evaluamos este último clasificador en el conjunto de test `X_test`, `y_test`.)

In [ ]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

#optimización
kfold = StratifiedKFold(n_splits=2, shuffle=True, random_state=45) #para nsplits=5 demora 35 min approx en google colab.

# pipeline
pipeline_knn = Pipeline([
     #('polynomial_features', PolynomialFeatures(degree=2)),
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier())
])
param_grid = {'knn__weights': ['uniform', 'distance'], #uniform es sin ponderación, weighted knn
              'knn__n_neighbors': np.arange(1,101,1), #1 a 100.
              'knn__metric': ['euclidean', 'manhattan', 'cosine']}


search = GridSearchCV(pipeline_knn, param_grid, scoring='recall', cv=kfold, verbose=4)
result = search.fit(X_train_undersampled, y_train_undersampled)

print(f'Mejor recall en el conj. de validación: {result.best_score_} para {result.best_params_}')

#reentreno con mejores
pipeline_knn.set_params(knn__n_neighbors=result.best_params_['knn__n_neighbors'],
                       knn__weights=result.best_params_['knn__weights'],
                       knn__metric=result.best_params_['knn__metric'])
pipeline_knn.fit(X_train_undersampled, y_train_undersampled)

#evaluamos en el conjunto de test
pred_test = pipeline_knn.predict(X_test)
f1score = metrics.f1_score(y_test, pred_test)
acc = metrics.accuracy_score(y_test, pred_test)
preci = metrics.precision_score(y_test, pred_test)
recall = metrics.recall_score(y_test, pred_test)

print("Para el modelo optimizado, métricas en el conjunto de test: recall = ", recall, ", F1 = ", f1score, ", acc = ", acc, ", precision = ", preci, )

Fitting 2 folds for each of 600 candidates, totalling 1200 fits
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=1, knn__weights=uniform;, score=0.704 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=1, knn__weights=uniform;, score=0.654 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=1, knn__weights=distance;, score=0.704 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=1, knn__weights=distance;, score=0.654 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=2, knn__weights=uniform;, score=0.538 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=2, knn__weights=uniform;, score=0.503 total time=   0.3s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=2, knn__weights=distance;, score=0.704 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=2, knn__weights=distance;, score=0.654 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=3, knn__weights=uniform;, score=0.758 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=3, knn__weights=uniform;, score=0.719 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=3, knn__weights=distance;, score=0.731 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=3, knn__weights=distance;, score=0.699 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=4, knn__weights=uniform;, score=0.672 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=4, knn__weights=uniform;, score=0.642 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=4, knn__weights=distance;, score=0.739 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=4, knn__weights=distance;, score=0.707 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=5, knn__weights=uniform;, score=0.806 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=5, knn__weights=uniform;, score=0.759 total time=   0.3s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=5, knn__weights=distance;, score=0.768 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=5, knn__weights=distance;, score=0.734 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=6, knn__weights=uniform;, score=0.743 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=6, knn__weights=uniform;, score=0.701 total time=   0.3s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=6, knn__weights=distance;, score=0.767 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=6, knn__weights=distance;, score=0.738 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=7, knn__weights=uniform;, score=0.819 total time=   0.4s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=7, knn__weights=uniform;, score=0.787 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=7, knn__weights=distance;, score=0.788 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=7, knn__weights=distance;, score=0.761 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=8, knn__weights=uniform;, score=0.775 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=8, knn__weights=uniform;, score=0.754 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=8, knn__weights=distance;, score=0.788 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=8, knn__weights=distance;, score=0.758 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=9, knn__weights=uniform;, score=0.834 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=9, knn__weights=uniform;, score=0.803 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=9, knn__weights=distance;, score=0.802 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=9, knn__weights=distance;, score=0.773 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=10, knn__weights=uniform;, score=0.791 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=10, knn__weights=uniform;, score=0.778 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=10, knn__weights=distance;, score=0.802 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=10, knn__weights=distance;, score=0.774 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=11, knn__weights=uniform;, score=0.827 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=11, knn__weights=uniform;, score=0.806 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=11, knn__weights=distance;, score=0.802 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=11, knn__weights=distance;, score=0.781 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=12, knn__weights=uniform;, score=0.807 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=12, knn__weights=uniform;, score=0.782 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=12, knn__weights=distance;, score=0.807 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=12, knn__weights=distance;, score=0.778 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=13, knn__weights=uniform;, score=0.842 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=13, knn__weights=uniform;, score=0.817 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=13, knn__weights=distance;, score=0.813 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=13, knn__weights=distance;, score=0.787 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=14, knn__weights=uniform;, score=0.807 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=14, knn__weights=uniform;, score=0.798 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=14, knn__weights=distance;, score=0.814 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=14, knn__weights=distance;, score=0.795 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=15, knn__weights=uniform;, score=0.847 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=15, knn__weights=uniform;, score=0.834 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=15, knn__weights=distance;, score=0.813 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=15, knn__weights=distance;, score=0.807 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=16, knn__weights=uniform;, score=0.813 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=16, knn__weights=uniform;, score=0.809 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=16, knn__weights=distance;, score=0.815 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=16, knn__weights=distance;, score=0.807 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=17, knn__weights=uniform;, score=0.845 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=17, knn__weights=uniform;, score=0.834 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=17, knn__weights=distance;, score=0.821 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=17, knn__weights=distance;, score=0.814 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=18, knn__weights=uniform;, score=0.831 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=18, knn__weights=uniform;, score=0.811 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=18, knn__weights=distance;, score=0.822 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=18, knn__weights=distance;, score=0.816 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=19, knn__weights=uniform;, score=0.850 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=19, knn__weights=uniform;, score=0.829 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=19, knn__weights=distance;, score=0.823 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=19, knn__weights=distance;, score=0.811 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=20, knn__weights=uniform;, score=0.829 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=20, knn__weights=uniform;, score=0.810 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=20, knn__weights=distance;, score=0.833 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=20, knn__weights=distance;, score=0.814 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=21, knn__weights=uniform;, score=0.847 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=21, knn__weights=uniform;, score=0.832 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=21, knn__weights=distance;, score=0.833 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=21, knn__weights=distance;, score=0.816 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=22, knn__weights=uniform;, score=0.831 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=22, knn__weights=uniform;, score=0.816 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=22, knn__weights=distance;, score=0.827 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=22, knn__weights=distance;, score=0.813 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=23, knn__weights=uniform;, score=0.851 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=23, knn__weights=uniform;, score=0.837 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=23, knn__weights=distance;, score=0.833 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=23, knn__weights=distance;, score=0.818 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=24, knn__weights=uniform;, score=0.841 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=24, knn__weights=uniform;, score=0.818 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=24, knn__weights=distance;, score=0.834 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=24, knn__weights=distance;, score=0.820 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=25, knn__weights=uniform;, score=0.854 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=25, knn__weights=uniform;, score=0.838 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=25, knn__weights=distance;, score=0.835 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=25, knn__weights=distance;, score=0.822 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=26, knn__weights=uniform;, score=0.841 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=26, knn__weights=uniform;, score=0.820 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=26, knn__weights=distance;, score=0.835 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=26, knn__weights=distance;, score=0.822 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=27, knn__weights=uniform;, score=0.854 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=27, knn__weights=uniform;, score=0.833 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=27, knn__weights=distance;, score=0.838 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=27, knn__weights=distance;, score=0.820 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=28, knn__weights=uniform;, score=0.843 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=28, knn__weights=uniform;, score=0.824 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=28, knn__weights=distance;, score=0.842 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=28, knn__weights=distance;, score=0.825 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=29, knn__weights=uniform;, score=0.855 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=29, knn__weights=uniform;, score=0.838 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=29, knn__weights=distance;, score=0.842 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=29, knn__weights=distance;, score=0.829 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=30, knn__weights=uniform;, score=0.838 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=30, knn__weights=uniform;, score=0.820 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=30, knn__weights=distance;, score=0.839 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=30, knn__weights=distance;, score=0.824 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=31, knn__weights=uniform;, score=0.842 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=31, knn__weights=uniform;, score=0.832 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=31, knn__weights=distance;, score=0.839 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=31, knn__weights=distance;, score=0.826 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=32, knn__weights=uniform;, score=0.838 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=32, knn__weights=uniform;, score=0.826 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=32, knn__weights=distance;, score=0.845 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=32, knn__weights=distance;, score=0.830 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=33, knn__weights=uniform;, score=0.847 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=33, knn__weights=uniform;, score=0.836 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=33, knn__weights=distance;, score=0.843 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=33, knn__weights=distance;, score=0.826 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=34, knn__weights=uniform;, score=0.847 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=34, knn__weights=uniform;, score=0.824 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=34, knn__weights=distance;, score=0.853 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=34, knn__weights=distance;, score=0.824 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=35, knn__weights=uniform;, score=0.859 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=35, knn__weights=uniform;, score=0.829 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=35, knn__weights=distance;, score=0.854 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=35, knn__weights=distance;, score=0.820 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=36, knn__weights=uniform;, score=0.853 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=36, knn__weights=uniform;, score=0.824 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=36, knn__weights=distance;, score=0.854 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=36, knn__weights=distance;, score=0.828 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=37, knn__weights=uniform;, score=0.862 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=37, knn__weights=uniform;, score=0.836 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=37, knn__weights=distance;, score=0.853 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=37, knn__weights=distance;, score=0.826 total time=   0.0s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=38, knn__weights=uniform;, score=0.857 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=38, knn__weights=uniform;, score=0.826 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=38, knn__weights=distance;, score=0.858 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=38, knn__weights=distance;, score=0.832 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=39, knn__weights=uniform;, score=0.865 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=39, knn__weights=uniform;, score=0.837 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=39, knn__weights=distance;, score=0.855 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=39, knn__weights=distance;, score=0.832 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=40, knn__weights=uniform;, score=0.851 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=40, knn__weights=uniform;, score=0.829 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=40, knn__weights=distance;, score=0.854 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=40, knn__weights=distance;, score=0.832 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=41, knn__weights=uniform;, score=0.862 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=41, knn__weights=uniform;, score=0.838 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=41, knn__weights=distance;, score=0.857 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=41, knn__weights=distance;, score=0.830 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=42, knn__weights=uniform;, score=0.855 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=42, knn__weights=uniform;, score=0.834 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=42, knn__weights=distance;, score=0.859 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=42, knn__weights=distance;, score=0.836 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=43, knn__weights=uniform;, score=0.861 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=43, knn__weights=uniform;, score=0.841 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=43, knn__weights=distance;, score=0.855 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=43, knn__weights=distance;, score=0.832 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=44, knn__weights=uniform;, score=0.853 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=44, knn__weights=uniform;, score=0.836 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=44, knn__weights=distance;, score=0.857 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=44, knn__weights=distance;, score=0.834 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=45, knn__weights=uniform;, score=0.859 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=45, knn__weights=uniform;, score=0.841 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=45, knn__weights=distance;, score=0.854 total time=   0.1s

### Optimización de hiperparámetros kNN con PCA

Repetiremos el proceso anterior pero esta vez con PCA

In [ ]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA

#optimización
kfold = StratifiedKFold(n_splits=2, shuffle=True, random_state=45) #para nsplits=5 demora 35 min approx en google colab.

# pipeline
pipeline_knn_pca = Pipeline([
     #('polynomial_features', PolynomialFeatures(degree=2)),
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95)),
    ('knn', KNeighborsClassifier())
])
param_grid = {'knn__weights': ['uniform', 'distance'],
              'knn__n_neighbors': np.arange(1,101,1),
              'knn__metric': ['euclidean', 'manhattan', 'cosine']}


search = GridSearchCV(pipeline_knn_pca, param_grid, scoring='recall', cv=kfold, verbose=4)
result = search.fit(X_train_undersampled, y_train_undersampled)

print(f'Mejor recall en el conj. de validación: {result.best_score_} para {result.best_params_}')

#reentreno con mejores
pipeline_knn_pca.set_params(knn__n_neighbors=result.best_params_['knn__n_neighbors'],
                       knn__weights=result.best_params_['knn__weights'],
                       knn__metric=result.best_params_['knn__metric'])
pipeline_knn_pca.fit(X_train_undersampled, y_train_undersampled)

#evaluamos en el conjunto de test
pred_test = pipeline_knn_pca.predict(X_test)
f1score = metrics.f1_score(y_test, pred_test)
acc = metrics.accuracy_score(y_test, pred_test)
preci = metrics.precision_score(y_test, pred_test)
recall = metrics.recall_score(y_test, pred_test)

print("Para el modelo optimizado, métricas en el conjunto de test: recall = ", recall, ", F1 = ", f1score, ", acc = ", acc, ", precision = ", preci, )

Fitting 2 folds for each of 600 candidates, totalling 1200 fits
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=1, knn__weights=uniform;, score=0.696 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=1, knn__weights=uniform;, score=0.646 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=1, knn__weights=distance;, score=0.696 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=1, knn__weights=distance;, score=0.646 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=2, knn__weights=uniform;, score=0.530 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=2, knn__weights=uniform;, score=0.507 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=2, knn__weights=distance;, score=0.696 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=2, knn__weights=distance;, score=0.646 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=3, knn__weights=uniform;, score=0.740 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=3, knn__weights=uniform;, score=0.723 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=3, knn__weights=distance;, score=0.722 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=3, knn__weights=distance;, score=0.702 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=4, knn__weights=uniform;, score=0.657 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=4, knn__weights=uniform;, score=0.628 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=4, knn__weights=distance;, score=0.727 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=4, knn__weights=distance;, score=0.697 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=5, knn__weights=uniform;, score=0.782 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=5, knn__weights=uniform;, score=0.749 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=5, knn__weights=distance;, score=0.751 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=5, knn__weights=distance;, score=0.721 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=6, knn__weights=uniform;, score=0.723 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=6, knn__weights=uniform;, score=0.684 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=6, knn__weights=distance;, score=0.759 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=6, knn__weights=distance;, score=0.725 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=7, knn__weights=uniform;, score=0.809 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=7, knn__weights=uniform;, score=0.775 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=7, knn__weights=distance;, score=0.780 total time=   0.0s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=7, knn__weights=distance;, score=0.741 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=8, knn__weights=uniform;, score=0.756 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=8, knn__weights=uniform;, score=0.737 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=8, knn__weights=distance;, score=0.780 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=8, knn__weights=distance;, score=0.743 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=9, knn__weights=uniform;, score=0.813 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=9, knn__weights=uniform;, score=0.791 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=9, knn__weights=distance;, score=0.780 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=9, knn__weights=distance;, score=0.758 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=10, knn__weights=uniform;, score=0.783 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=10, knn__weights=uniform;, score=0.771 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=10, knn__weights=distance;, score=0.788 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=10, knn__weights=distance;, score=0.761 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=11, knn__weights=uniform;, score=0.829 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=11, knn__weights=uniform;, score=0.810 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=11, knn__weights=distance;, score=0.798 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=11, knn__weights=distance;, score=0.774 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=12, knn__weights=uniform;, score=0.802 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=12, knn__weights=uniform;, score=0.791 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=12, knn__weights=distance;, score=0.802 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=12, knn__weights=distance;, score=0.773 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=13, knn__weights=uniform;, score=0.833 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=13, knn__weights=uniform;, score=0.814 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=13, knn__weights=distance;, score=0.807 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=13, knn__weights=distance;, score=0.777 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=14, knn__weights=uniform;, score=0.817 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=14, knn__weights=uniform;, score=0.790 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=14, knn__weights=distance;, score=0.809 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=14, knn__weights=distance;, score=0.783 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=15, knn__weights=uniform;, score=0.833 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=15, knn__weights=uniform;, score=0.820 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=15, knn__weights=distance;, score=0.810 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=15, knn__weights=distance;, score=0.786 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=16, knn__weights=uniform;, score=0.811 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=16, knn__weights=uniform;, score=0.802 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=16, knn__weights=distance;, score=0.810 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=16, knn__weights=distance;, score=0.794 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=17, knn__weights=uniform;, score=0.822 total time=   0.3s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=17, knn__weights=uniform;, score=0.821 total time=   0.4s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=17, knn__weights=distance;, score=0.807 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=17, knn__weights=distance;, score=0.794 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=18, knn__weights=uniform;, score=0.809 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=18, knn__weights=uniform;, score=0.807 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=18, knn__weights=distance;, score=0.811 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=18, knn__weights=distance;, score=0.799 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=19, knn__weights=uniform;, score=0.827 total time=   0.3s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=19, knn__weights=uniform;, score=0.833 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=19, knn__weights=distance;, score=0.817 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=19, knn__weights=distance;, score=0.805 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=20, knn__weights=uniform;, score=0.818 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=20, knn__weights=uniform;, score=0.813 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=20, knn__weights=distance;, score=0.819 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=20, knn__weights=distance;, score=0.807 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=21, knn__weights=uniform;, score=0.838 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=21, knn__weights=uniform;, score=0.829 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=21, knn__weights=distance;, score=0.818 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=21, knn__weights=distance;, score=0.807 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=22, knn__weights=uniform;, score=0.823 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=22, knn__weights=uniform;, score=0.818 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=22, knn__weights=distance;, score=0.819 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=22, knn__weights=distance;, score=0.809 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=23, knn__weights=uniform;, score=0.837 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=23, knn__weights=uniform;, score=0.829 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=23, knn__weights=distance;, score=0.822 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=23, knn__weights=distance;, score=0.807 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=24, knn__weights=uniform;, score=0.827 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=24, knn__weights=uniform;, score=0.818 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=24, knn__weights=distance;, score=0.822 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=24, knn__weights=distance;, score=0.810 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=25, knn__weights=uniform;, score=0.843 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=25, knn__weights=uniform;, score=0.830 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=25, knn__weights=distance;, score=0.823 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=25, knn__weights=distance;, score=0.811 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=26, knn__weights=uniform;, score=0.831 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=26, knn__weights=uniform;, score=0.828 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=26, knn__weights=distance;, score=0.827 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=26, knn__weights=distance;, score=0.817 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=27, knn__weights=uniform;, score=0.847 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=27, knn__weights=uniform;, score=0.836 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=27, knn__weights=distance;, score=0.830 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=27, knn__weights=distance;, score=0.817 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=28, knn__weights=uniform;, score=0.839 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=28, knn__weights=uniform;, score=0.828 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=28, knn__weights=distance;, score=0.835 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=28, knn__weights=distance;, score=0.817 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=29, knn__weights=uniform;, score=0.845 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=29, knn__weights=uniform;, score=0.833 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=29, knn__weights=distance;, score=0.834 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=29, knn__weights=distance;, score=0.816 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=30, knn__weights=uniform;, score=0.845 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=30, knn__weights=uniform;, score=0.828 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=30, knn__weights=distance;, score=0.843 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=30, knn__weights=distance;, score=0.818 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=31, knn__weights=uniform;, score=0.851 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=31, knn__weights=uniform;, score=0.836 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=31, knn__weights=distance;, score=0.839 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=31, knn__weights=distance;, score=0.821 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=32, knn__weights=uniform;, score=0.846 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=32, knn__weights=uniform;, score=0.830 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=32, knn__weights=distance;, score=0.845 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=32, knn__weights=distance;, score=0.826 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=33, knn__weights=uniform;, score=0.849 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=33, knn__weights=uniform;, score=0.837 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=33, knn__weights=distance;, score=0.841 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=33, knn__weights=distance;, score=0.821 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=34, knn__weights=uniform;, score=0.843 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=34, knn__weights=uniform;, score=0.826 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=34, knn__weights=distance;, score=0.842 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=34, knn__weights=distance;, score=0.820 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=35, knn__weights=uniform;, score=0.851 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=35, knn__weights=uniform;, score=0.833 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=35, knn__weights=distance;, score=0.842 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=35, knn__weights=distance;, score=0.818 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=36, knn__weights=uniform;, score=0.846 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=36, knn__weights=uniform;, score=0.824 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=36, knn__weights=distance;, score=0.843 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=36, knn__weights=distance;, score=0.816 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=37, knn__weights=uniform;, score=0.854 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=37, knn__weights=uniform;, score=0.830 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=37, knn__weights=distance;, score=0.846 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=37, knn__weights=distance;, score=0.814 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=38, knn__weights=uniform;, score=0.849 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=38, knn__weights=uniform;, score=0.828 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=38, knn__weights=distance;, score=0.846 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=38, knn__weights=distance;, score=0.820 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=39, knn__weights=uniform;, score=0.855 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=39, knn__weights=uniform;, score=0.834 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=39, knn__weights=distance;, score=0.847 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=39, knn__weights=distance;, score=0.821 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=40, knn__weights=uniform;, score=0.850 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=40, knn__weights=uniform;, score=0.829 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=40, knn__weights=distance;, score=0.845 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=40, knn__weights=distance;, score=0.824 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=41, knn__weights=uniform;, score=0.855 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=41, knn__weights=uniform;, score=0.836 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=41, knn__weights=distance;, score=0.843 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=41, knn__weights=distance;, score=0.825 total time=   0.1s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=42, knn__weights=uniform;, score=0.851 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=42, knn__weights=uniform;, score=0.829 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=42, knn__weights=distance;, score=0.846 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=42, knn__weights=distance;, score=0.822 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=43, knn__weights=uniform;, score=0.854 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=43, knn__weights=uniform;, score=0.834 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=43, knn__weights=distance;, score=0.849 total time=   0.1s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=43, knn__weights=distance;, score=0.822 total time=   0.3s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=44, knn__weights=uniform;, score=0.850 total time=   0.3s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=44, knn__weights=uniform;, score=0.829 total time=   0.4s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=44, knn__weights=distance;, score=0.850 total time=   0.2s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=44, knn__weights=distance;, score=0.826 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=45, knn__weights=uniform;, score=0.853 total time=   0.3s
[CV 2/2] END knn__metric=euclidean, knn__n_neighbors=45, knn__weights=uniform;, score=0.834 total time=   0.2s
[CV 1/2] END knn__metric=euclidean, knn__n_neighbors=45, knn__weights=distance;, score=0.850 total time=   0.1s

### ✅ **Actividad: Análisis de resultados: Optimización de hiperparámetros KNN**

Ejecute el código de esta notebook y analice los siguientes casos:

1. kNN sin PCA
2. kNN con PCA

Comente sus resultados analizando los valores de recall, f1 score, accuracy y precisión en el conjunto de test.

Cuál es mejor en términos de recall?

Cuál demora menos en entrenar? Vale la pena usar PCA?

Por qué cree que el recall es una métrica más adecuada para este problema? Tip: El recall está relacionado a los falsos negativos. Analice por qué es importante disminuir los falsos negativos en el churn.

# ✅ **Actividad**: Bayesian Hyperparameter Optimization

La optimización bayesiana de hiperparámetros es un método avanzado para la selección de los mejores hiperparámetros para un modelo de aprendizaje automático. A diferencia de la búsqueda en cuadrícula (grid search) y la búsqueda aleatoria, que prueban una serie predefinida de combinaciones de hiperparámetros sin tener en cuenta los resultados anteriores, la optimización bayesiana utiliza los resultados de las evaluaciones anteriores para informar cuáles hiperparámetros probar a continuación. Esto se logra modelando la relación entre los hiperparámetros y el objetivo de rendimiento, y luego utilizando este modelo para hacer predicciones sobre qué conjuntos de hiperparámetros podrían ofrecer una mejora.

Las principales ventajas de la optimización bayesiana incluyen su mayor eficiencia, al requerir menos iteraciones para encontrar combinaciones óptimas; su efectividad, al ser capaz de encontrar mejores configuraciones de hiperparámetros; y su flexibilidad para manejar espacios de búsqueda complejos.

Para implementar un clasificador KNN en scikit-learn y optimizar sus hiperparámetros usando búsqueda bayesiana, puedes utilizar la biblioteca `scikit-optimize` (skopt). Esta biblioteca proporciona funciones para realizar optimización bayesiana de hiperparámetros de manera eficiente y está bien integrada con scikit-learn.



Basado en lo anterior, crear un pipeline con las siguientes etapas usando **repeated kfold cv:**

1. Scaler
2. KNN

Enseguida, pptimizar los param. de KNN usando optimización bayesiana. Finalmente, evaluar en el conjunto de test.

Tip: Ver BayesSearchCV en https://machinelearningmastery.com/scikit-optimize-for-hyperparameter-tuning-in-machine-learning/

# ✅ **Actividad: Voronoi 2D y 3D con TSNE (opcional)**

1. **Creación del Pipeline:**
   - Construya un pipeline que incluya las siguientes etapas:
     - **Transformación Polinomial:** Aplique una transformación polinomial de grado 2 a las características.
     - **Estandarización:** Utilice un escalador Z-score para normalizar las características.
     - **Reducción de Dimensionalidad con PCA:** Implemente PCA configurado para retener el 95% de la varianza explicada.
     - **Clasificador:** Utilice el algoritmo K-Nearest Neighbors con los siguientes hiperparámetros 'knn__metric': `'euclidean', 'knn__n_neighbors': 100, 'knn__weights': 'distance'`
2. Genere el Voronoi Tesselation (VT) del clasificador anterior en 2D y 3D. Utilice TSNE como reductor de dimensionalidad para visualizar el VT

# ✅ Actividad: k vs train recall and val recall


1. **Creación del Pipeline:**
   - Construya un pipeline que incluya las siguientes etapas:
     - **Estandarización:** Utilice un escalador Z-score para normalizar las características.
     - **Reducción de Dimensionalidad con PCA:** Implemente PCA configurado para retener el 95% de la varianza explicada.
     - **Clasificador:** Utilice el algoritmo K-Nearest Neighbors.

2. **Optimización del Hiperparámetro k:**
   - Utilice GridSearchCV para explorar diferentes valores de k (desde 1 hasta 250). Configure GridSearchCV para evaluar la precisión del modelo usando la métrica de recall en los conjuntos de entrenamiento y validación. Mantenga fijos todos los demás hiperparámetros.

3. **Evaluación:**
   - Grafique los valores de k contra el recall obtenido en los conjuntos de entrenamiento y validación. Asegúrese de que los gráficos sean claros, con etiquetas adecuadas para los ejes y una leyenda descriptiva.

4. **Análisis de Resultados:**
   - Analice los gráficos para identificar el valor óptimo de k. Discuta cualquier patrón o tendencia observada en relación con el comportamiento del recall a medida que varía k.

In [ ]:
#here your code




# ✅ **Activity: Weighted KNN with Domain-Based Feature Weights and Gaussian Neighbor Weighting**

### 1. **Custom Distance Metric (Domain-Based Feature Weights)**

* Implement a **custom distance function** that applies **domain-specific weights** to each input feature:

  $$
  d(x, x') = \sqrt{\sum_i w_i (x_i - x_i')^2}
  $$
* The function or method must accept:

  * Two input samples $x, x'$
  * An array of feature weights $w = [w_1, w_2, ..., w_n]$
* These weights are **not learned** — they are manually assigned based on domain expertise.


---

### 2. **Gaussian-Based Neighbor Weighting**

* Fix the number of neighbors to **k = 50**.
* Apply a **Gaussian function** to weight each neighbor:

  $$
  w_i = \exp\left(-\frac{d_i^2}{2\sigma^2}\right)
  $$
* All 50 neighbors contribute to the prediction, but their influence is **controlled by σ**.
* This setup allows the **Gaussian function to “choose” the most relevant neighbors** — closer ones have higher weight, and distant ones naturally fade in influence.
* ❗Note that the weights $w_i$ from Gaussian-based neighbor weighting are not the same as those from the domain-specific weights (feature weighting).

---

### 3. **Hyperparameter Optimization**

* Optimize only the **σ (sigma)** parameter.
* Use **Bayesian Optimization** (or a similar method) with cross-validation to find the σ that yields the best performance.

---

### 4. **Evaluation**

* Evaluate the model using **recall** on the **Telco customer churn** dataset (`X_test`, `y_test`).
* Compare your model’s **recall** to a **baseline KNN classifier** using:

  * Euclidean distance
  * Uniform weighting (equal neighbor influence)

---

### 5. **Analysis**

* Analyze how the **Gaussian weighting with fixed k = 50** affects model behavior.
* Reflect on:

  * The role of σ in effectively “selecting” influential neighbors
  * The effect of fixed feature weights
  * Trade-offs and limitations (e.g., sensitivity to σ)
  * Potential extensions, such as adaptive weighting


### 💡 **Hint: Using `BaseEstimator` for Your Custom KNN Classifier**

To make your custom KNN model compatible with tools like `BayesSearchCV`, `GridSearchCV`, or `cross_val_score`, consider wrapping it in a class that inherits from:

* `sklearn.base.BaseEstimator`
* `sklearn.base.ClassifierMixin`

This gives you:

* Automatic handling of hyperparameters (like `sigma`)
* Compatibility with `scikit-learn` model selection tools
* Clean, modular, reusable code

---

### 🧱 Minimal Starting Point

Here’s a simple class to get started:

```python
from sklearn.base import BaseEstimator, ClassifierMixin
import numpy as np

class GaussianWeightedKNN(BaseEstimator, ClassifierMixin):
    def __init__(self, sigma=1.0, k=50, feature_weights=None):
        self.sigma = sigma
        self.k = k
        self.feature_weights = feature_weights

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y
        return self

    def predict(self, X):
        # You will implement the logic for prediction here,
        # using the Gaussian weights on neighbors and weights on features.
        pass
```

Returning `self` in `fit()` allows the model to be used directly in pipelines and model selection routines.

---


### 🧠 Why is the `fit` Method Simple in KNN?

KNN is a **lazy learner**:

* It **does not build an internal model** during training.
* Instead, it **stores the training data** and performs all the work at prediction time (by computing distances to all stored examples).

That’s why the `fit` method just **memorizes** the training data and labels.

In [ ]:
#here your code